return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    --event = { "BufReadPost", "BufNewFile" },
    -- cmd = { "TSUpdateSync" },
    opts = {
        sync_install = false,
        auto_install = true,    
        highlight = {
          enable = true,
          additional_vim_regex_highlighting = false,
        },
        indent = { enable = true },
        ensure_installed = {
            "bash",
            "python",
            "query",
            "javascript",
            "c",
            "vim",
            "bicep",
            "c_sharp",
            "gitignore",
            "go",
            "gomod",
            "gosum",
            "gowork",
            "html",
            "http",
            "json",
            "lua",
            "luadoc",
            "luap",
            "markdown",
            "markdown_inline",
            "nix",
            "odin",
            "powershell",
            "regex",
            "rust",
            "templ",
            "toml",
            "vimdoc",
            "yaml",
        },
    },
    config = function(_, opts)
        require("nvim-treesitter.configs").setup(opts)
    end,
}
